version: '2'
services:
    points-app:
        image: points
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://points-postgresql:5432/points
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=points-elasticsearch:9300
        ports:
            - 8080:8080
    points-postgresql:
        extends:
            file: postgresql.yml
            service: points-postgresql
    points-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: points-elasticsearch
